import mongoose from "mongoose";

const drugsDbSchema = mongoose.Schema({
    // id: {type: String, unique: true},
    id: String,
    sysDateCreated: String,
    sysDateUpdated: String,
    sysUserId: String,
    nazwa: {type: String, unique: true},
    rodzajPrep: String,
    nazPowStos: String,
    postac:String,
    dawka: String,
    podmOdpow: String,
    typProc: String,
    nrPozw: String,
    waznPozw: String,
    kodAtc: String,
    substCzynna: String,
    ean: String,
    wielkoscOpak: String,
    jednWielkOpak: String,
    katDostOpak: String,
    skasowane: String,
    nrEu: String,
    dystrRown: String,
    nazPostDawka: String,
    zawOpak: String,
    terminWejscia: String,
    okresObowiazDec: String,
    grupaLimit: String,
    urzCenaZb: String,
    cenaHurtBrut: String,
    cenaDetal: String,
    wysokLimitu: String,
    zakrWskazRef: String,
    zakrWskazPoza: String,
    poziomOdpl: String,
    wysokDopl: String,
    katalog: String,
    refund: String
});

export const Drugs = mongoose.model("Drugs", drugsDbSchema);
